A=input('ingrese el año en curso: ')
B=input('ingrese el nombre de la primera persona: ')
C=input('ingrese el año de nacimiento de la primera persona: ')
A=int(A)
C=int(C)
print('Edad que cumple este año: ', A - C, 'años')
D=input('ingrese el nombre de la segunda persona: ')
E=input('ingrese el año de nacimiento de la segunda persona: ')
E=int(E)
print('Edad que cumple este año: ', A - E, 'años')
F=input('ingrese el nombre de la tercera persona: ')
G=input('ingrese el año de nacimiento de la tercera persona: ')
G=int(G)
print('Edad que cumple este año: ', A - G, 'años')